export {
  beginScrollRestoreLock,
  captureScrollAnchor,
  clearScrollAnchor,
  clearScrollRestoreLock,
  exportScrollDebugSnapshot,
  getPinnedScrollAnchor,
  getScrollAnchor,
  isFollowingTail,
  isScrollPinned,
  isScrollRestoreLocked,
  persistScrollAnchor,
  pinScrollAnchor,
  restoreScrollAnchor,
  restoreScrollAnchorFromBottom,
  restoreScrollIntent,
  saveScrollAnchor,
  saveScrollAnchorOnHide,
  touchScrollAnchor,
  unpinScrollAnchor,
  FOLLOW_TAIL_THRESHOLD,
  SCROLL_RESTORE_LOCK_MS,
} from "@/features/terminal/surfaces/terminalScrollState";
export type {
  TerminalScrollAnchor,
  TerminalScrollDebugSnapshot,
} from "@/features/terminal/surfaces/terminalScrollState";
