/** Webview host channel emitted for trusted human interaction inside a preview guest. */
export const PREVIEW_GUEST_HUMAN_INPUT_CHANNEL = "mcode:browser-human-input";

/** Main-process channel for one trusted, unsuppressed pointer click. */
export const PREVIEW_GUEST_CLIPBOARD_TRUST_CHANNEL = "mcode:browser-clipboard-trust";

/** Guest preload channel that reserves trusted events generated by agent CDP input. */
export const PREVIEW_GUEST_AGENT_INPUT_CHANNEL = "mcode:browser-agent-input";

/** Trusted guest interaction categories that transfer control from an agent to the human. */
export const PREVIEW_GUEST_HUMAN_INPUT_KINDS = [
  "keyboard",
  "pointer",
  "touch",
  "wheel",
] as const;

/** One trusted human interaction sent from the fixed preview guest preload. */
export interface PreviewGuestHumanInputMessage {
  readonly kind: (typeof PREVIEW_GUEST_HUMAN_INPUT_KINDS)[number];
}

/** Bounded allowance sent before agent CDP input reaches the guest preload. */
export interface PreviewGuestAgentInputAllowance extends PreviewGuestHumanInputMessage {
  readonly action: "allow";
  readonly token: string;
  readonly generation: number;
  readonly count: number;
  readonly expiresAt: number;
}

/** Exact allowance revocation sent when its CDP dispatch fails. */
export interface PreviewGuestAgentInputRevocation {
  readonly action: "revoke";
  readonly token: string;
  readonly generation: number;
}

const MAX_AGENT_INPUT_ALLOWANCES = 32;

/** Tracks short-lived agent event allowances so synthetic trusted events never claim human control. */
export class PreviewGuestInputSuppressor {
  private readonly allowances = new Map<string, PreviewGuestAgentInputAllowance>();

  /** Accepts one bounded allowance from the trusted host process. */
  allow(input: unknown, now = Date.now()): boolean {
    const candidate = parseAgentInputAllowance(input, now);
    if (!candidate) return false;
    this.removeExpired(now);
    this.evictOldestAllowance(candidate.token);
    this.allowances.set(candidate.token, candidate);
    return true;
  }

  /** Revokes only the exact token generation whose CDP dispatch failed. */
  revoke(input: unknown, now = Date.now()): boolean {
    if (!input || typeof input !== "object" || Array.isArray(input)) return false;
    const candidate = input as Partial<PreviewGuestAgentInputRevocation>;
    if (candidate.action !== "revoke") return false;
    if (typeof candidate.token !== "string" || !Number.isSafeInteger(candidate.generation)) return false;
    this.removeExpired(now);
    const allowance = this.allowances.get(candidate.token);
    if (!allowance || allowance.generation !== candidate.generation) return false;
    this.allowances.delete(candidate.token);
    return true;
  }

  /** Consumes one matching, unexpired agent event allowance. */
  consume(kind: PreviewGuestHumanInputMessage["kind"], now = Date.now()): boolean {
    this.removeExpired(now);
    for (const [token, allowance] of this.allowances) {
      if (allowance.kind !== kind) continue;
      if (allowance.count === 1) this.allowances.delete(token);
      else this.allowances.set(token, { ...allowance, count: allowance.count - 1 });
      return true;
    }
    return false;
  }

  /** Removes expired allowances and returns the number released. */
  expire(now = Date.now()): number {
    return this.removeExpired(now);
  }

  private removeExpired(now: number): number {
    let removed = 0;
    for (const [token, allowance] of this.allowances) {
      if (allowance.expiresAt >= now) continue;
      this.allowances.delete(token);
      removed += 1;
    }
    return removed;
  }

  private evictOldestAllowance(token: string): void {
    if (this.allowances.has(token)) return;
    if (this.allowances.size < MAX_AGENT_INPUT_ALLOWANCES) return;
    const oldestToken = this.allowances.keys().next().value;
    if (typeof oldestToken === "string") this.allowances.delete(oldestToken);
  }
}

function parseAgentInputAllowance(
  input: unknown,
  now: number,
): PreviewGuestAgentInputAllowance | null {
  if (!isAgentInputAllowanceRecord(input)) return null;
  if (!hasValidAgentInputIdentity(input)) return null;
  if (!hasValidAgentInputCount(input.count)) return null;
  if (!hasValidAgentInputExpiry(input.expiresAt, now)) return null;
  return input;
}

function isAgentInputAllowanceRecord(
  input: unknown,
): input is PreviewGuestAgentInputAllowance {
  if (!input || typeof input !== "object" || Array.isArray(input)) return false;
  return (input as { action?: unknown }).action === "allow";
}

function hasValidAgentInputIdentity(input: PreviewGuestAgentInputAllowance): boolean {
  return (
    input.token.length >= 1 &&
    input.token.length <= 128 &&
    Number.isSafeInteger(input.generation) &&
    input.generation >= 1 &&
    PREVIEW_GUEST_HUMAN_INPUT_KINDS.includes(input.kind)
  );
}

function hasValidAgentInputCount(count: number): boolean {
  return Number.isInteger(count) && count >= 1 && count <= 16;
}

function hasValidAgentInputExpiry(expiresAt: number, now: number): boolean {
  return Number.isFinite(expiresAt) && expiresAt >= now && expiresAt <= now + 5_000;
}

/** Maps a trusted DOM input event to the narrow webview-host takeover message. */
export function toPreviewGuestHumanInputMessage(
  eventType: string,
  isTrusted: boolean,
): PreviewGuestHumanInputMessage | null {
  if (!isTrusted) return null;
  switch (eventType) {
    case "keydown":
      return { kind: "keyboard" };
    case "pointerdown":
      return { kind: "pointer" };
    case "touchstart":
      return { kind: "touch" };
    case "wheel":
      return { kind: "wheel" };
    default:
      return null;
  }
}
