/** Provider-neutral operating guide for the visible Mcode Browser v2 contract. */
export const MCODE_BROWSER_GUIDE = `Mcode Browser v2 Operating Guide (authenticated Mcode provider sessions only)

Apply this guide automatically when the user asks to open, inspect, test, debug, or interact with the visible Browser. The user does not need to invoke $mcode-browser.

- Intent: use mcode-browser for Mcode's shared Preview. Tabs may run while the Browser panel is hidden and be revealed later. Do not launch a separate browser or profile, and never compete with direct user input.
- Target selection: browser_open creates one agent-owned background tab, makes it sticky, and returns tab metadata plus an observationRef, not a semantic page observation. Call browser_inspect before the first action unless the returned result includes sufficient current snapshot evidence. Use browser_tabs to select or claim another tab and to release, close, or finalize controlled tabs. For elements, prefer semanticId from the latest inspection, then role plus accessibleName, then CSS or coordinates only without a semantic target. Targets must come from the latest inspection; never guess ambiguous matches.
- Observation: browser_inspect is the authority for current readiness, tabs, capabilities, constraints, diagnostics, revision, and observationRef. Tool discovery alone does not prove that a Browser target is ready.
- Safe sequencing: bind every mutation to the latest observationRef and a fresh idempotency key. browser_act accepts up to eight ordered steps with a deadline no greater than 60 seconds and stops at the first failure, interruption, deadline, or invalidation. After a non-navigation mutation, verify the intended postcondition with an assert step when possible or a fresh inspection. Navigation and reload end the batch at the document boundary; inspect before another mutation.
- Interruption: cooperative user input invalidates the observation. Explicit Stop or Take control interrupts execution. Release held input, preserve completed effects, and yield to the user.
- Recovery: inspect receipts and effect classification before another call. An applied receipt proves the action effect, not the intended page outcome. Effects do not roll back and Mcode never replays mutations automatically. Follow exactly one recovery instruction: inspect, reopen, wait, yield_to_user, or do_not_retry.
- Evidence: request includeScreenshot only when visual, layout, focus, or appearance evidence matters or the user asks for visual proof, not after every action. Before answering, verify every user-facing success claim against current page evidence.
- Final disposition: use browser_tabs finalize when Browser work ends. Release claimed user tabs. Close agent-created tabs unless the user needs a handoff or deliverable.
- Privileged evaluation: use browser_evaluate only when the live capability advertises it. Apply the same observation, idempotency, interruption, receipt, effect, and recovery rules as other mutations.
`;
